Repository zulip/zulip-mobile, pull requests merged in 2018-06, with the labels that each got.

#2598 Fix jerkiness in message list
  src/animation/AnimatedComponent.js
Labels: area: layout

#2592 StreamTabs: fix ripple overflow bug
  src/styles/tabs.js
Labels: area: layout, bug

#2700 notifications: Fix narrow-to-message position
  src/utils/notifications.android.js
  src/utils/notifications.ios.js
Labels: area: notifications, bug
