Repository zulip/zulip-mobile, pull requests merged in 2020-04, with the labels that each got.

#3991 group-pm: fix colorHashFromString
  src/utils/__tests__/color-test.js
  src/utils/color.js
Labels: P0 critical

#4029 webview build: Build to an intermediate staging directory for Android.
  android/app/webviewAssets.gradle
Labels: P1 high-priority

#4073 api types: `realm_user_groups` is absent prior to v1.8.0.
  src/api/initialDataTypes.js
  src/api/modelTypes.js
Labels: api migrations, bite size
