Repository zulip/zulip-mobile, pull requests merged in 2020-05, with the labels that each got.

#4043 Fix scroll-on-resize to avoid jumping from bottom
  src/webview/js/generatedEs3.js
  src/webview/js/js.js
Labels: P1 high-priority, a-message list

#3890 readme: Make it more clear that contributions are welcome.
  README.md
Labels: a-documentation

#3868 SearchMessagesScreen: Store fetched messages in Redux store.
  src/search/SearchMessagesScreen.js
Labels: severe: crash

#3852 android build: Update to AndroidX.
  android/app/build.gradle
  android/app/src/main/java/com/zulipmobile/CustomTabsAndroid.java
  android/app/src/main/java/com/zulipmobile/CustomTabsHelper.java
  android/app/src/main/java/com/zulipmobile/notifications/NotificationsModule.java
  android/build.gradle
  android/gradle.properties
  package.json
  tools/postinstall
  yarn.lock
Labels: P1 high-priority, a-Android
