Repository zulip/zulip-mobile, pull requests merged in 2020-03, with the labels that each got.

#3953 tests: Rename 'aux/' directory to 'auxiliary/'.
  jest.config.js
  src/__tests__/auxiliary/lolex.js
  src/__tests__/metatests.js
  src/api/__tests__/queueMarkAsRead-test.js
  src/utils/__tests__/async-test.js
Labels: P1 high-priority

#3929 docs/build-run: Add more troubleshooting cases.
  docs/howto/build-run.md
Labels: a-documentation

#3947 ios notifs: Consume "background queue" so notifs navigate from backgr…
  src/boot/AppEventHandlers.js
  src/notification/index.js
Labels: P1 high-priority

#3969 prettier: use Babylon (babel-flow) as the parser
  .prettierrc
Labels: a-tools, bite size

#3963 emoji search: Search for query-string anywhere in the emoji name.
  src/emoji/__tests__/data-test.js
  src/emoji/data.js
Labels: a-emoji
