Repository zulip/zulip-mobile, pull requests merged in 2021-03, with the labels that each got.

#4473 eslint: Specify Jest version in config.
  .eslintrc.yaml
Labels: a-tools

#4507 api types: Drop `name` from subscription update events.
  src/actionTypes.js
  src/subscriptions/__tests__/subscriptionsReducer-test.js
Labels: api migrations

#4537 Fix appearance of "@" icon in the home screen.
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: upstream: other
