Repository zulip/zulip-mobile, pull requests merged in 2021-12, with the labels that each got.

#5155 action types: Sync update-message event type with doc
  src/actionTypes.js
  src/message/__tests__/messagesReducer-test.js
Labels: a-data-sync, P1 high-priority

#4980 unreadModel: Handle moving messages between topics/streams.
  src/unread/__tests__/unreadModel-test.js
  src/unread/unreadModel.js
Labels: a-redux, a-data-sync, P1 high-priority

#5167 deps: Upgrade RN to v0.64.3, from v0.64.2
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: dependencies
