Repository zulip/zulip-mobile, pull requests merged in 2021-04, with the labels that each got.

#4588 user: Expand checks in getHaveServerData.
  src/users/userSelectors.js
Labels: P0 critical, a-multi-org, a-redux, severe: crash

#4585 ZulipMobile: Add and use RootErrorBoundary.
  src/RootErrorBoundary.js
  src/ZulipMobile.js
Labels: P1 high-priority

#4580 deps: Upgrade to @react-native-community/cameraroll v4.0.4.
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: dependencies

#4596 notifications: Add Timestamp.
  android/app/src/main/java/com/zulipmobile/notifications/FCMPushNotifications.kt
Labels: a-Android, a-notifications

#4627 event: Log error but don't throw, if no active account at eventToAction.
  src/events/eventToAction.js
Labels: a-data-sync

#4632 i18n: Rename id_ID -> id.
  flow-typed/translations.js
  src/boot/store.js
  src/i18n/messages.js
  src/settings/languages.js
  static/translations/messages_id.json
Labels: a-i18n

#4689 migrations: Add one that should have been added in #4491.
  src/boot/store.js
Labels: P1 high-priority
