Repository zulip/zulip-mobile, pull requests merged in 2021-09, with the labels that each got.

#4928 deps: Upgrade jest-expo to 42.1.0, the latest.
  package.json
  yarn.lock
Labels: dependencies

#4982 Fix react-intl libdef, on the path to RN v0.64 upgrade.
  flow-typed/react-intl_vx.x.x.js
Labels: P1 high-priority

#4985 flow: Add missing error codes in some new suppressions.
  src/__flow-tests__/reactUtils-test.js
Labels: P1 high-priority

#4831 notifications: Add more detail to "realm_uri ambiguous" error.
  src/notification/index.js
Labels: a-notifications

#4989 deps: Remove two peer-deps we don't need anymore (helpful for RN v0.64 upgrade).
  package.json
  yarn.lock
Labels: P1 high-priority, dependencies

#5015 deps: Run `yarn upgrade`.
  ios/Podfile.lock
  yarn.lock
Labels: dependencies
