Repository zulip/zulip-mobile, pull requests merged in 2021-06, with the labels that each got.

#4733 Fix: Logout gives endless loading screen
  src/nav/AppNavigator.js
  src/withHaveServerDataGate.js
Labels: P1 high-priority, a-multi-org, bug

#4779 deps: Remove prop-types from devDependencies.
  package.json
Labels: dependencies

#4787 dependabot: Remove config file.
  .github/dependabot.yml
Labels: a-tools

#4794 accountsReducer [nfc]: Followups on handling restart events
  src/account/accountsReducer.js
Labels: api migrations

#4801 RawLabel: Fix crash when text is empty string.
  src/common/RawLabel.js
Labels: P1 high-priority, severe: crash

#4819 import: Work around broken imports of '.'.
  src/common/CountOverlay.js
  src/common/FullScreenLoading.js
  src/common/LoadingBanner.js
  src/common/ZulipTextButton.js
  src/notification/notificationActions.js
Labels: P1 high-priority, severe: crash

#4827 deps: Run `yarn upgrade`.
  ios/Podfile.lock
  yarn.lock
Labels: dependencies
