Repository zulip/zulip-mobile, pull requests merged in 2022-06, with the labels that each got.

#5407 tsflower: Make patches more reproducible between machines/developers
  tools/tsflower
  types/patches/0001-format-Add-a-few-prettier-ignores-to-work-around-a-P.patch
  types/patches/0002-tsflower-rnsac-Fix-ReadOnlyArray-reference-to-litera.patch
  types/patches/0003-upstream-rnav-ReadOnlyArray-on-NavigationState-prope.patch
  types/patches/0004-upstream-rnav-ReadOnly-on-ResetState-as-param-of-res.patch
  types/patches/0005-upstream-rnav-Fix-type-parameter-defaults-that-don-t.patch
  types/patches/0006-upstream-rnav-Fix-State-tparam-bound-in-NavigationPr.patch
  types/patches/0007-upstream-rnav-Covariant-indexers-in-create-Navigator.patch
  types/patches/0008-upstream-rnav-Covariant-indexer-in-ParamListBase.patch
  types/patches/0009-upstream-rnav-create-Navigator-type-surely-means-to-.patch
  types/patches/0010-upstream-rnav-On-create-Navigator-cut-redundant-wron.patch
  types/patches/0011-upstream-optional-rnav-Fix-NavigationRoute-to-supply.patch
  types/patches/0012-irreducible-rnav-Make-action-types-exact.patch
  types/patches/0013-irreducible-rnav-Covariant-type-parameters-on-variou.patch
  types/patches/0014-irreducible-rnav-EventMap-types-exact-and-covariant.patch
  types/patches/0015-tsflower-rnav-Fix-a-parenthesization-of-intersection.patch
  types/patches/0016-tsflower-Handle-TS-reference-pragma-for-React-in-mat.patch
  types/patches/0017-tsflower-Resolve-re-export-indirection-on-CommonActi.patch
  types/patches/0018-tsflower-Fix-import-type-of-classes.patch
  types/patches/0019-tsflower-Better-substitution-for-React.ForwardRefExo.patch
  types/patches/0020-tsflower-Manually-rewrite-Pick-from-TS-default-libra.patch
  types/patches/0021-tsflower-Substitute-for-React.ReactText.patch
  types/patches/0022-adhoc-rnav-Manually-approximate-conditional-in-Route.patch
  types/patches/0023-adhoc-rnav-Manually-approximate-conditionals-in-Even.patch
  types/patches/0024-rnav-Fix-odd-initialRouteName-index-signature-error.patch
Labels: a-tools

#5416 example data: Fix date_joined on users to always be valid
  src/__tests__/lib/exampleData.js
Labels: P1 high-priority

#5418 realm: Handle missing realm_default_external_accounts before 2.1
  src/api/initialDataTypes.js
  src/realm/__tests__/realmReducer-test.js
  src/realm/realmReducer.js
Labels: P1 high-priority

#5417 msglist: Respect user's display_emoji_reaction_users setting
  src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.android
  src/webview/__tests__/__snapshots__/generateInboundEventEditSequence-test.js.snap.ios
  src/webview/__tests__/generateInboundEventEditSequence-test.js
  src/webview/html/message.js
  src/webview/static/base.css
  static/translations/messages_en.json
Labels: P1 high-priority, server release goal

#5430 emoji: Cut `congratulations` alias to reflect server update
  src/emoji/codePointMap.js
Labels: a-emoji
