Repository zulip/zulip-mobile, pull requests merged in 2022-02, with the labels that each got.

#5220 emoji: Add two Wordle emoji names to unicodeCodeByName
  src/emoji/codePointMap.js
Labels: P1 high-priority, a-emoji

#5226 Fix major startup lag, by using Animated.loop instead of giant duration
  src/animation/AnimatedRotateComponent.js
Labels: upstream: RN, P1 high-priority

#5239 sentry: Add breadcrumb for Zulip event type (and op when present)
  flow-typed/@sentry/react-native_v2.x.x.js
  src/api/eventTypes.js
  src/events/eventActions.js
Labels: P1 high-priority
