Repository zulip/zulip-mobile, pull requests merged in 2022-03, with the labels that each got.

#5293 gitattributes: Suppress diffs on renamed Jest snapshot files
  .gitattributes
Labels: a-tools

#5296 android build: Split up APKs per ABI
  android/app/build.gradle
  docs/howto/build-run.md
  docs/howto/release.md
  tools/changelog
Labels: a-Android, P1 high-priority

#5297 UserItem: Fix recent regression where UnreadCount was misaligned
  src/users/UserItem.js
Labels: P1 high-priority
