Repository zulip/zulip-mobile, pull requests merged in 2022-12, with the labels that each got.

#5576 ios build: Work around "signing requires development team" build error
  ios/Podfile
  ios/Podfile.lock
Labels: a-iOS

#5580 nix: Add a shell.nix file
  shell.nix
Labels: a-tools

#5587 [toward #5102, refuse ancient servers] RealmInputScreen: Improve validation logic a bit
  src/start/RealmInputScreen.js
  static/translations/messages_en.json
Labels: P1 high-priority

#5588 android build [nfc]: Organize dependencies a bit
  android/app/build.gradle
Labels: a-Android

#5600 topics tests: Start type-checking; use example data
  src/topics/__tests__/topicsReducer-test.js
Labels: P1 high-priority

#5591 [toward #5102, refuse ancient servers] login: Equalize user-facing errors across both api.getUserSettings calls
  src/account/AccountPickScreen.js
  src/message/fetchActions.js
  src/start/RealmInputScreen.js
  static/translations/messages_en.json
Labels: P1 high-priority

#5608 android: Fix animated GIFs in lightbox, by getting Fresco version automatically
  android/app/build.gradle
Labels: a-Android, upstream: RN, P1 high-priority, a-lightbox

#5622 flow: Forbid object-as-map when constructing `Immutable.Map`s
  docs/style.md
  src/chat/__tests__/narrowsReducer-test.js
  src/chat/__tests__/narrowsSelectors-test.js
  src/message/__tests__/fetchActions-test.js
  src/pm-conversations/__tests__/pmConversationsSelectors-test.js
  src/storage/__tests__/replaceRevive-test.js
Labels: P1 high-priority

#5613 model: Make REGISTER_COMPLETE reset some state we forgot about
  src/chat/__tests__/fetchingReducer-test.js
  src/chat/fetchingReducer.js
  src/topics/__tests__/topicsReducer-test.js
  src/topics/topicsReducer.js
  src/typing/__tests__/typingReducer-test.js
  src/typing/typingReducer.js
Labels: P1 high-priority
