Repository zulip/zulip-mobile, pull requests merged in 2022-04, with the labels that each got.

#5317 react-native-webview libdef: Small fixes, before more involved ones
  flow-typed/react-native-webview_v11.x.x.js
Labels: P1 high-priority

#5312 ComposeBox: Convert to a function component!
  src/compose/ComposeBox.js
Labels: P1 high-priority

#5330 react-native-webview libdef: Trim out some not-so-helpful definitions
  flow-typed/react-native-webview_v11.x.x.js
Labels: P1 high-priority

#5334 compat: Show "unsupported" banner for 2.1.x, too
  src/common/ServerCompatBanner.js
Labels: P1 high-priority

#5339 streamsReducer tests: Start type-checking; use example data
  src/streams/__tests__/streamsReducer-test.js
Labels: P1 high-priority

#5335 deps: Run `yarn upgrade`.
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: P1 high-priority, dependencies

#5343 ios: Update "SPEC CHECKSUMS" for DoubleConversion and glog
  ios/Podfile.lock
Labels: a-iOS

#5354 api types: Fix ApiResponseServerSettings to make a new property optional
  src/api/settings/getServerSettings.js
Labels: P1 high-priority

#5327 ComposeBox conversion: some followups
  src/compose/ComposeBox.js
Labels: P1 high-priority

#5368 deps: Temporarily use fork for @react-navigation/bottom-tabs
  package.json
  yarn.lock
Labels: P1 high-priority
